### ISSUE TITLE
Thanks for sharing a fantastic demo

### ISSUE THREAD

**Issue by sadevn** [webcat12345/konva-demo#19]
I checked your demo app.
It's really good to start my project. Thanks for your sharing.
I have experience in Angular and Nestjs, looking forward to working with you.

**Comment by webcat12345** [comment]
You are welcome. It's just a simple demo and please ask any question if you have. I heard from sis today and just waiting for you.

**Comment by sadevn** [comment]
Yeah, it's simple app but it's worth to refer.
I am learning Nestjs from scratch. My email is kit-kat.0225@outlook.com. Have a good weekend.

**Comment by webcat12345** [comment]
Could you please let me know your Chinese name?

**Comment by sadevn** [comment]
My name is 李军 Li Jun

**Comment by sadevn** [comment]
Please let me know the project description.
I need it to open slack.
We need to discuss the project in detail via skype in many eyes.
My skype email is kit-kat.0225@outlook.com. please send me hi there.

**Comment by sadevn** [comment]
Is there any problem?
And please provide me with an Angular project using Nestjs as backend.

**Comment by webcat12345** [comment]
I have sent the slack invitation. Please accept the invite asap.
